import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class ServiceService {
  country = [
    {
      name: '茉丘莉',
      score0: 100,
      score1: null,
      score2: null,
      score3: null,
      score4: null,
      score5: null,
      score6: null,
      score7: null,
      sPoint0: 9,
      sPoint1: null,
      sPoint2: null,
      sPoint3: null,
      sPoint4: null,
      sPoint5: null,
      sPoint6: null,
      sPoint7: null,
      percent: null,
      s1bad: 0,
      s2bad: 0,
      scourgeArray: [],
      scourgeScore: 0,
      totalScore: 0,
      totalSPoint: 0,
    },
    {
      name: '韋納施',
      score0: 100,
      score1: null,
      score2: null,
      score3: null,
      score4: null,
      score5: null,
      score6: null,
      score7: null,
      sPoint0: 9,
      sPoint1: null,
      sPoint2: null,
      sPoint3: null,
      sPoint4: null,
      sPoint5: null,
      sPoint6: null,
      sPoint7: null,
      percent: null,
      s1bad: 0,
      s2bad: 0,
      scourgeArray: [],
      scourgeScore: 0,
      totalScore: 0,
      totalSPoint: 0,
    },
    {
      name: '瑪爾司',
      score0: 100,
      score1: null,
      score2: null,
      score3: null,
      score4: null,
      score5: null,
      score6: null,
      score7: null,
      sPoint0: 9,
      sPoint1: null,
      sPoint2: null,
      sPoint3: null,
      sPoint4: null,
      sPoint5: null,
      sPoint6: null,
      sPoint7: null,
      percent: null,
      s1bad: 0,
      s2bad: 0,
      scourgeArray: [],
      scourgeScore: 0,
      totalScore: 0,
      totalSPoint: 0,
    },
    {
      name: '硃筆忒',
      score0: 100,
      score1: null,
      score2: null,
      score3: null,
      score4: null,
      score5: null,
      score6: null,
      score7: null,
      sPoint0: 9,
      sPoint1: null,
      sPoint2: null,
      sPoint3: null,
      sPoint4: null,
      sPoint5: null,
      sPoint6: null,
      sPoint7: null,
      percent: null,
      s1bad: 0,
      s2bad: 0,
      scourgeArray: [],
      scourgeScore: 0,
      totalScore: 0,
      totalSPoint: 0,
    },
    {
      name: '莎特瑞',
      score0: 100,
      score1: null,
      score2: null,
      score3: null,
      score4: null,
      score5: null,
      score6: null,
      score7: null,
      sPoint0: 9,
      sPoint1: null,
      sPoint2: null,
      sPoint3: null,
      sPoint4: null,
      sPoint5: null,
      sPoint6: null,
      sPoint7: null,
      percent: null,
      s1bad: 0,
      s2bad: 0,
      scourgeArray: [],
      scourgeScore: 0,
      totalScore: 0,
      totalSPoint: 0,
    },
  ];

  mission: any = [
    {
      isMission1: false,
      select1: null,
      isMission2: false,
      select2: null,
      isMission3: false,
    },
    {
      isMission1: false,
      select1: null,
      isMission2: false,
      select2: null,
      isMission3: false,
    },
    {
      isMission1: false,
      select1: null,
      isMission2: false,
      select2: null,
      isMission3: false,
    },
    {
      isMission1: false,
      select1: null,
      isMission2: false,
      select2: null,
      isMission3: false,
    },
    {
      isMission1: false,
      select1: null,
      isMission2: false,
      select2: null,
      isMission3: false,
    },
  ];

  getData() {
    return this.country; //呼叫getData的方法的時候，回傳資料
  }
  constructor() {}
}
