import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class ServiceService {
  country = [
    {
      name: '魔羯座',
      score0: 100,
      score1: null,
      score2: null,
      score3: null,
      score4: null,
      score5: null,
      score6: null,
      score7: null,
      sPoint0: 9,
      sPoint1: null,
      sPoint2: null,
      sPoint3: null,
      sPoint4: null,
      sPoint5: null,
      sPoint6: null,
      sPoint7: null,
      percent: null,
    },
    {
      name: '水瓶座',
      score0: 100,
      score1: null,
      score2: null,
      score3: null,
      score4: null,
      score5: null,
      score6: null,
      score7: null,
      sPoint0: 9,
      sPoint1: null,
      sPoint2: null,
      sPoint3: null,
      sPoint4: null,
      sPoint5: null,
      sPoint6: null,
      sPoint7: null,
      percent: null,
    },
    {
      name: '天蠍座',
      score0: 100,
      score1: null,
      score2: null,
      score3: null,
      score4: null,
      score5: null,
      score6: null,
      score7: null,
      sPoint0: 9,
      sPoint1: null,
      sPoint2: null,
      sPoint3: null,
      sPoint4: null,
      sPoint5: null,
      sPoint6: null,
      sPoint7: null,
      percent: null,
    },
    {
      name: '天秤座',
      score0: 100,
      score1: null,
      score2: null,
      score3: null,
      score4: null,
      score5: null,
      score6: null,
      score7: null,
      sPoint0: 9,
      sPoint1: null,
      sPoint2: null,
      sPoint3: null,
      sPoint4: null,
      sPoint5: null,
      sPoint6: null,
      sPoint7: null,
      percent: null,
    },
    {
      name: '巨蟹座',
      score0: 100,
      score1: null,
      score2: null,
      score3: null,
      score4: null,
      score5: null,
      score6: null,
      score7: null,
      sPoint0: 9,
      sPoint1: null,
      sPoint2: null,
      sPoint3: null,
      sPoint4: null,
      sPoint5: null,
      sPoint6: null,
      sPoint7: null,
      percent: null,
    },
  ];

  getData() {
    return this.country; //呼叫getData的方法的時候，回傳資料
  }
  constructor() {}
}
